name:        live-reload
grade:       stable
version:     v0.1.0
summary:     Live-reload is a build-framework agnostic website reloading tool.
description: Live-reload is a build-framework agnostic website reloading tool
confinement: strict

base: core18

apps:
  live-reload:
    command: bin/live-reload
    plugs: ['network']

parts:
  live-reload:
    source: .
    plugin: nodejs
    nodejs-package-manager: npm
    build-packages: ['libcurl4-openssl-dev', 'git']