name:        live-reload
grade:       stable
version:     v0.1.0
summary:     Live-reload is a build-framework agnostic tool for reloading a static-site during development .
description: Live-reload is a build-framework agnostic tool for reloading a static-site during development

confinement: strict

base: core18

apps:
  polonium:
    command: bin/live-reload
    plugs: ['network']

parts:
  polonium:
    source: .
    plugin: nodejs
    nodejs-package-manager: npm
    build-packages: ['libcurl4-openssl-dev', 'git']